### ISSUE TITLE
pandas is incompatible with numpy < 1.20.3

### ISSUE THREAD

**Issue by YiqianGu** [STOmics/SAW#122]
Hi team,

My singularity version is 3.8.5, and I used SAW_7.1.sif.
When I run this pipeline, an error happened. I copied the error part and upload a log file.
I really appreciate your help! 

Thanks,
Yiqian

Traceback (most recent call last):
  File "v3.4.2/Tissuecut.py", line 261, in <module>
  File "v3.4.2/Tissuecut.py", line 257, in main
  File "v3.4.2/Tissuecut.py", line 236, in tslib
  File "v3.4.2/Tissuecut.py", line 33, in drawStatImg
  File "/usr/local/python3/lib/python3.8/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "/usr/local/python3/lib/python3.8/site-packages/seaborn/rcmod.py", line 7, in <module>
    from . import palettes
  File "/usr/local/python3/lib/python3.8/site-packages/seaborn/palettes.py", line 9, in <module>
    from .utils import desaturate, get_color_cycle
  File "/usr/local/python3/lib/python3.8/site-packages/seaborn/utils.py", line 11, in <module>
    import pandas as pd
  File "/usr/local/python3/lib/python3.8/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/usr/local/python3/lib/python3.8/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/python3/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py", line 23, in <module>
    raise ImportError(
ImportError: this version of pandas is incompatible with numpy < 1.20.3
your numpy version is 1.20.0.

Please upgrade numpy to >= 1.20.3 to use this pandas version

[script.log](https://github.com/user-attachments/files/15920494/script.log)

**Comment by Jinghao-Chen** [comment]
Hi, It is recommended that upgrade the numpy package in your environment, or change to a clean environment(such as using conda) to run SAW.

**Comment by YiqianGu** [comment]
Hi Clouate, I guess this error is not related with my environment. Instead, it shows that the version of numpy from SAW_7.1.sif is not compatible with the pandas from SAW_7.1.sif.

**Comment by YiqianGu** [comment]
solved by "singularity exec SAW_7.1.sif pip3 install numpy==1.20.3"
