### ISSUE TITLE
Step07.report TypeError: float() argument must be a string or a number, not 'Vividict'

### ISSUE THREAD

**Issue by Changzhanhe** [STOmics/SAW#133]
Hello, when I run step 07 to generate 07.report folder, it will encounter error like this:
Traceback (most recent call last):
  File "report/handleReport_main.py", line 451, in <module>
  File "report/handleReport_main.py", line 398, in main
  File "report/generate_analysis_report.py", line 320, in generate_html_function
  File "report/generate_analysis_report.py", line 1612, in get_sun_fig
  File "report/read_json.py", line 43, in __init__
  File "report/read_json.py", line 192, in from_alignment
  File "report/DataHanding.py", line 17, in tran_data
TypeError: float() argument must be a string or a number, not 'Vividict'

Any idea to solve this problem? 
Thanks a lot!

**Comment by Jinghao-Chen** [comment]
@Changzhanhe Hi, could you provide the 00.mapping/*Log.final.out ? The reason for this error is that the contents of the .Log.final.out file were not correctly read.

**Comment by Jinghao-Chen** [comment]
@Changzhanhe Hi, it seems that FBS has reported your problem to us. We found that the genome mapping step of one of your lanes was interrupted. The relevant information would be fed back to you through FBS.

**Comment by Changzhanhe** [comment]
My problem has been solved. Thank you very much for your reply!
