### ISSUE TITLE
Step03 failure by SAW-A40001

### ISSUE THREAD

**Issue by regenerativescience** [STOmics/SAW#135]
Hello,

I encountered an issue while running `stereoPipeline_v7.1.sh`. During the `register` execution, the following error occurred:

> SAW-A40001: The version of 0.1.0 is too low to deliver automatic registration.

According to [this link](https://en.stomics.tech/col658/list.html), the SAW-A40001 error indicates a "Parameter missing" issue. However, I have verified that the directories and files used as parameters do exist.

I'm unsure what the problem might be. Could you please provide guidance on how to resolve this issue?

Due to the need to run the script on a shared high-performance computer, I made the following modifications to `stereoPipeline_v7.1.sh`:
- Commented out `export SINGULARITY_BIND`
- Changed `singularity exec ${sif}` to `singularity exec --bind ${PWD}:${PWD} ${sif}`

Here are the standard output and standard error logs from the `.sh` file:

output
~~~ 
Wed Jul 31 10:43:01 JST 2024  singularity check: pass, and singularity path is /home/center/opt/x86_64/apps/singularity/4.1.2/bin/singularity
Wed Jul 31 10:43:01 JST 2024  singularity image file check: file exist and SIF path is /home/z40265r/tool/SAW_7.1.sif
Wed Jul 31 10:43:01 JST 2024 => splitMask, compute CID count and predict the memory of mapping start......
Your sequencing reads are in Q40 format.
Wed Jul 31 10:43:36 JST 2024 => CID mapping, adapter filtering and RNA alignment start......
~~~ mapping - Exp56_S1_L001_R1.fastq.gz ~~~
Wed Jul 31 16:50:46 JST 2024 => merge barcode reads count tables start......
Q40
Wed Jul 31 16:50:49 JST 2024 => annotation, deduplication, and generate gene expression matrix start......
chr cnt:39 genecnt:32902
umi end 13
Wed Jul 31 17:22:07 JST 2024 => image processing and registration start.......
Namespace(conf='/data/group1/z40265r/RawData/Stereo/C02536A6_SC_20240724_164012_2.2.1.ipr', core=16, func=<class '__main__.Pipeline'>, gpu='-1', group=None, input='/data/group1/z40265r/RawData/Stereo/C02536A6_SC_20240724_164012_2.2.1.tar.gz', output='/data/group1/z40265r/analysis/Stereo/Exp056/Result/03.register', protein=None, vis='/data/group1/z40265r/analysis/Stereo/Exp056/Result/02.count/C02536A6.raw.gef', whether_cell=True) []
~~~

error
~~~
[INFO 20240731-17-22-22 p333 check_output main.py:124] The output result path is successfully created.
I0731 17:22:22.088440 333 main.py:124] The output result path is successfully created.
[INFO 20240731-17-22-22 p333 check_output main.py:133] The ipr file copied successfully.
I0731 17:22:22.100615 333 main.py:133] The ipr file copied successfully.
[INFO 20240731-17-22-23 p333 check_image main.py:87] The image compression package needs to decompress the .tif data format.
I0731 17:22:23.531097 333 main.py:87] The image compression package needs to decompress the .tif data format.
[INFO 20240731-17-22-25 p333 check_image main.py:99] Verify image data /data/group1/z40265r/RawData/Stereo/C02536A6_SC_20240724_164012_2.2.1.tar.gz file for registration
I0731 17:22:25.036128 333 main.py:99] Verify image data /data/group1/z40265r/RawData/Stereo/C02536A6_SC_20240724_164012_2.2.1.tar.gz file for registration
[INFO 20240731-17-22-25 p333 check_image main.py:105] Image verification successful.
I0731 17:22:25.036351 333 main.py:105] Image verification successful.
[ERRO 20240731-17-22-25 p333 create_auto_manual_attrs main.py:224] SAW-A40001:    The version of 0.1.0 is too low to deliver automatic registration.
E0731 17:22:25.037603 333 main.py:224] SAW-A40001:    The version of 0.1.0 is too low to deliver automatic registration.
Traceback (most recent call last):
  File "register-v4.3.2/register/main.py", line 539, in <module>
  File "register-v4.3.2/register/main.py", line 535, in main
  File "register-v4.3.2/register/main.py", line 349, in __init__
  File "register-v4.3.2/register/main.py", line 225, in create_auto_manual_attrs
Exception: SAW-A40001:    The version of 0.1.0 is too low to deliver automatic registration.
~~~

Thank you for your assistance.

Best regards,

**Comment by Jinghao-Chen** [comment]
@regenerativescience Hi, this error was due to the version of ImageStudio you used(2.2.1) being too low and not suitable for SAW 7.x. You could use the latest version of ImageStudio (>=3.0.0) and StereoMap(>=3.0.0).

**Comment by regenerativescience** [comment]
@Clouate 

Thank you for your prompt response.

If possible, could you please provide guidance on one more point? Where can I find the compatibility table between the versions of ImageStudio and SAW?

Thank you for your assistance.

**Comment by regenerativescience** [comment]
I was able to find the compatibility table between the versions of ImageStudio and SAW at [this link](https://enfile.stomics.tech/Stereo-seq%20SAW%20FAQ%20version%20A3.pdf).
