### ISSUE TITLE
Exception: SAW-A40002: Unable to get track transformed tif from 

### ISSUE THREAD

**Issue by wzhang42** [STOmics/SAW#162]
Hi, STOmics pipeline developer,
     Thanks for your developing such as amazing Spatial-omics tools.  I have successfully run several batches from the download data from your sharing.  
     But, today,  I am now running a real mouse liver data and got the following exception message, and have no idea on how to solve it.  Much appreciated for your suggestions and opinion.
        
Wenchao
        
.....
WARNING: While bind mounting '/research_jude/rgs01_jude/groups/wugrp/projects/NTU/common/ST/JunYang2/00.Rawdata/image:/research_jude/rgs01_jude/groups/wugrp/projects/NTU/common/ST/JunYang2/00.Rawdata/image': destination is already in the mount point list
[INFO 20241030-14-14-29 p1412979 check_output main.py:124] The output result path is successfully created.
I1030 14:14:29.472567 1412979 main.py:124] The output result path is successfully created.
[INFO 20241030-14-14-29 p1412979 check_output main.py:133] The ipr file copied successfully.
I1030 14:14:29.610981 1412979 main.py:133] The ipr file copied successfully.
[INFO 20241030-14-14-35 p1412979 check_image main.py:87] The image compression package needs to decompress the .tif data format.
I1030 14:14:35.858066 1412979 main.py:87] The image compression package needs to decompress the .tif data format.
[INFO 20241030-14-14-42 p1412979 check_image main.py:99] Verify image data /research_jude/rgs01_jude/groups/wugrp/projects/NTU/common/ST/JunYang2/00.Rawdata/image/A04539G4_SC_20240927_155033_4.0.1.tar.gz file for registration
I1030 14:14:42.358193 1412979 main.py:99] Verify image data /research_jude/rgs01_jude/groups/wugrp/projects/NTU/common/ST/JunYang2/00.Rawdata/image/A04539G4_SC_20240927_155033_4.0.1.tar.gz file for registration
[INFO 20241030-14-14-42 p1412979 check_image main.py:105] Image verification successful.
I1030 14:14:42.358510 1412979 main.py:105] Image verification successful.
[INFO 20241030-14-14-42 p1412979 create_auto_manual_attrs main.py:268] Pipeline need to handle these subtask: ['cellseg'].
I1030 14:14:42.363354 1412979 main.py:268] Pipeline need to handle these subtask: ['cellseg'].
**[ERRO 20241030-14-14-42 p1412979 get_track_image main.py:40] SAW-A40002:    Unable to get track transformed tif from .
E1030 14:14:42.364732 1412979 main.py:40] SAW-A40002:    Unable to get track transformed tif from .**
Traceback (most recent call last):
  File "register-v4.3.2/register/main.py", line 539, in <module>
  File "register-v4.3.2/register/main.py", line 535, in main
  File "register-v4.3.2/register/main.py", line 356, in __init__
  File "register-v4.3.2/register/main.py", line 485, in run
  File "register-v4.3.2/register/main.py", line 41, in get_track_image
Exception: SAW-A40002:    Unable to get track transformed tif from .
Command exited with non-zero status 1
	Command being timed: "singularity exec ../SAW_7.1.sif register -i /research_jude/rgs01_jude/groups/wugrp/projects/NTU/common/ST/JunYang2/00.Rawdata/image/A04539G4_SC_20240927_155033_4.0.1.tar.gz -c /research_jude/rgs01_jude/groups/wugrp/projects/NTU/common/ST/JunYang2/00.Rawdata/image/A04539G4_SC_20240927_155033_4.0.1.ipr -v /research_jude/rgs01_jude/groups/wugrp/projects/NTU/common/ST/JunYang2/STOmics_Pipeline_Out/02.count/A04539G4.raw.gef -w True --core 12 -o /research_jude/rgs01_jude/groups/wugrp/projects/NTU/common/ST/JunYang2/STOmics_Pipeline_Out/03.register"
	User time (seconds): 15.87
	System time (seconds): 4.69
	Percent of CPU this job got: 71%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:28.60
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 373200
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 1629
	Minor (reclaiming a frame) page faults: 151817
	Voluntary context switches: 7983
	Involuntary context switches: 366557
	Swaps: 0
	File system inputs: 247056
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1

**Comment by Jinghao-Chen** [comment]
@wzhang42 Hi, may I ask how you obtained A04539G4_SC_20240927_155033_4.0.1.tar.gz and A04539G4_SC_20240927_155033_4.0.1.ipr? What software is used and what operations were performed?

**Comment by Jinghao-Chen** [comment]
> @wzhang42 Hi, may I ask how you obtained A04539G4_SC_20240927_155033_4.0.1.tar.gz and A04539G4_SC_20240927_155033_4.0.1.ipr? What software is used and what operations were performed?

In addition, could you show the contents of the 03.register directory and the files in A04539G4_SC_20240927_155033_4.0.1.tar.gz?

**Comment by wzhang42** [comment]
Hi, Clouate, many thanks for your reply.    
1.)   I got the fastq reads and image related  A04539G4_SC_20240927_155033_4.0.1.tar.gz and A04539G4_SC_20240927_155033_4.0.1.ipr from my PI which, I believe, is  originally from Pacgenomics.   I just used SAW_7.1.sif to run stereoPipeline_v7.1.sh in HPC cluster.  
2.).  03.register]$ ls
20241030-14-14-29.log  A04539G4_SC_20241030_141429_4.0.1.ipr  ssDNA

3.) $ tar -xvzf A04539G4_SC_20240927_155033_4.0.1.tar.gz
$ls
A04539G4_SC_20240927_155033_4.0.1.ipr  A04539G4_SC_20240927_155033_4.0.1.tar.gz  ssDNA

The inner A04539G4_SC_20240927_155033_4.0.1.tar.gz can not be extracted again.


So, you means the A04539G4_SC_20240927_155033_4.0.1.tar.gz is broken, or are not in the right format, right?

**Comment by Jinghao-Chen** [comment]
@wzhang42 Hi, I have checked the content above. I found that this tar.gz and ipr are output after SAW v8 analysis (you can see their version number is v4.0.1, you can confirm this with your PI), and they are not compatible with SAW v7, which is one of the reasons for this error. If you want to analyze this data, you could choose to use ImageStudio v3 to processs ImageQC on the image files in the ssDNA directory and then use SAW v7 to analyze. Or upgrade to SAW v8 to analyze this tar.gz.
For the relevant instructions of  SAW v8 and StereoMap v4(ImageStudio has been integrated into StereoMap), please refer to the following websites
SAW: https://en.stomics.tech/service/new-saw-operation-manual.html
StereoMap: https://en.stomics.tech/service/stereoMap-operation-manual.html

**Comment by wzhang42** [comment]
Hi, Clouate, thank you so much for response. I have installed ImageStudio v3 in my laptop.  I prefer to process the ssDNA and use SAW v7 to analyze. But could you provide a little bit more details /instructions for me to start from the ssDNA folder and generate a a new .tar.gz that compatible for SAW v7?

**Comment by Jinghao-Chen** [comment]
Of course, what is the content of ssDNA dierctory? A tif/tiff format file?

**Comment by wzhang42** [comment]
ssDNA]$ ls
20240918_SC_A04539G4_STO073-1.czi  A04539G4
 and A04539G4 is folder which contain a lot of .tif files,  such as. AF488_0_0_m0.tif  AF488_1_1_m10.tif, ...

**Comment by Jinghao-Chen** [comment]
Firstly, download the `A04539G4_SC_20240927_155033_4.0.1.tar.gz` to your laptop.
Then, start the Image Quality Control module of ImageStudio, and drag the `A04539G4_SC_20240927_155033_4.0.1.tar.gz` to run Image QC.
After QC is completed, find the ImageStudioWorkspace\QC directory in the same path as the imagestudio installation directory. There will be a directory named with the chip number+timestamp, which stores the tar.gz and ipr files adapted to SAW v7.
In addition, you could also choose to use `20240918_SC_A04539G4_STO073-1.czi` for QC in the first step

**Comment by wzhang42** [comment]
Thanks so much. Your instruction is very useful. I have successfully finished the pipeline running.
