### ISSUE TITLE
version `GCC_4.8.0' not found

### ISSUE THREAD

**Issue by SuqinYang** [STOmics/SAW#166]
Hello, I downloaded the SAW from "https://cdn-newfile.stomics.tech/saw-8.1.0.tar.gz" and unzipped it using the code "tar -xzf saw-8.1.0.tar.gz". But when I ran "./saw-8.1.0/bin/saw count --help" and I got the error :

Traceback (most recent call last):
  File "/tmp/onefile_257079_1731754644_119708/saw", line 20, in <module>
  File "/tmp/onefile_257079_1731754644_119708/h5py/__init__.py", line 33, in <module h5py>
  File "/tmp/onefile_257079_1731754644_119708/h5py/version.py", line 17, in <module h5py.version>
  File "/tmp/onefile_257079_1731754644_119708/numpy/__init__.py", line 140, in <module numpy>
  File "/tmp/onefile_257079_1731754644_119708/numpy/core/__init__.py", line 23, in <module numpy.core>
  File "/tmp/onefile_257079_1731754644_119708/numpy/core/multiarray.py", line 10, in <module numpy.core.multiarray>
  File "/tmp/onefile_257079_1731754644_119708/numpy/core/overrides.py", line 6, in <module numpy.core.overrides>
ImportError: /share/apps/software/MatlabR2016a/sys/os/glnxa64/libgcc_s.so.1: version `GCC_4.8.0' not found (required by /tmp/onefile_257079_1731754644_119708/numpy/core/../../libgfortran-040039e1.so.5.0.0)

I don't have root access，do you have any good suggestions for fixing this error? Thank you so much!

**Comment by Jinghao-Chen** [comment]
Hi, could you confirm whether the file `saw-8.1.1/anaconda/lib/libgcc_s.so.1` and the soft link `saw-8.1.1/anaconda/x86_64-conda-linux-gnu/lib/libgcc_s.so.1` exists? Is the MD5 of saw-8.1.0.tar.gz correct and the unzip process complete? Or you could try to remove '/share/apps/software/MatlabR2016a/sys/os/glnxa64' from your environment variable LD_LIBRARY_PATH, or use conda to create a new empty environment and try again

**Comment by SuqinYang** [comment]
Thank you so much! The error was solved. But when I ran saw count, another error occurred: "UserWarning: GUROBI error: HostID mismatch",do you have any ideas to solve this error? Thank you so much!
My code:
saw count \
    --id="testSAW8.1.0" \
    --sn="C04687E314" \
    --omics=transcriptomics \
    --kit-version="Stereo-seq T FF V1.3" \
    --sequencing-type="PE75_50+100" \
    --chip-mask="./mask/C04687E314.barcodeToPos.h5" \
    --organism="mouse" \
    --tissue="eyeball" \
    --fastqs="./rawdata" \
    --image-tar="./image/C04687E314_SC_20240926_173246_4.1.0.tar.gz" \
    --reference=./reference/STAR_SJ100/"

**Comment by Jinghao-Chen** [comment]
Hi, which step did the error occur? Can I check the entire log content of `testSAW8.1.0/pipeline-logs/log`? This may be caused by environment conflicts. SAW 8.1.1 has made some optimizations for this situation. You could try it or run SAW with an empty conda environment.

**Comment by SuqinYang** [comment]
I tried saw8.1.1 and the same error occurred. The log file has been sent to the attachment.

**Comment by Jinghao-Chen** [comment]
This seems to be an error in genome alignment. If possible, could you provide `STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/V350284656_L03_read_1.run.log, V350284656_L03_read_1.Log.out and V350284656_L03_read_1.bcPara`? In addition, you could also confirm whether the running memory is sufficient, about 100g of memory is required (can be set by the --memory parameter), and the integrity of the fastq file, such as `zcat fq.gz | tail` to check whether the fq file is complete.

**Comment by SuqinYang** [comment]
Hi, the running memory is sufficient and the fq files are complete. The file V350284656_L03_read_1.bcPara is not in my output files and the V350284656_L03_read_1.run.log file has been sent to the attachment. Here's all the files I got in directory ALIGNMENT.
![figure1](https://github.com/user-attachments/assets/8c579bc8-503a-448c-84f1-97ab385ed01a)

**Comment by Jinghao-Chen** [comment]
@SuqinYang Thanks, could you provide `log_map` and `V350284656_L03_read_1.Log.out`? In addition, did you use `saw makeRef` to build your reference? Could you show the files in the STAR directory and the running log at that time?

**Comment by SuqinYang** [comment]
Hi,I've fixed this error, the problem is that I used the STAR index downloaded directly, and now I can solve the above problem with "saw makeRef". But I'm getting new errors and the log files has been sent to the attachment. Any files you need, please tell me, thank you so much!
The log files:
"B04372C211/STEREO_ANALYSIS_WORKFLOW_PROCESSING/log_tissuecut" and "pipeline-logs/log"

**Comment by Jinghao-Chen** [comment]
@SuqinYang Could you try the following code and show the output? (If I wrote the saw path wrong, please change it to the correct one.)
```
pip list | grep tensorflow

saw_path='/data/home/linlab/yangsuqin/software/saw-8.1.0'
${saw_path}/anaconda/bin/python -m site
export PYTHONPATH=$PYTHONPATH:${saw_path}/anaconda/lib/python3.8/site-packages
${saw_path}/anaconda/bin/python -m site
```
After running the above code, if your analysis path has not been deleted, re-run `saw count` with the same command in the same terminal to see if the error message still appears?

**Comment by SuqinYang** [comment]
Thank you so much and the problems were solved!

**Comment by Jinghao-Chen** [comment]
@SuqinYang Glad to hear that. Can I know how you solved it? If you use the code I provided, it means that the problem may be due to the conflict between SAW's tensorflow and your python environment's tensorflow. If you need to analyze other data later, you could consider installing tensorflow 2.7.0 or add the above code to export PYTHONPATH before running saw count.

**Comment by SuqinYang** [comment]
Hi, I tried the codes you provided and then re-ran "saw count" with the same command. Maybe it's because I didn't add the saw_path to the environment variables, so the "saw count" didn't call the python in the saw_path but called the python in my environment. Thank you so much!
The codes I tried: 
"saw_path='/data/home/linlab/yangsuqin/software/saw-8.1.0'
${saw_path}/anaconda/bin/python -m site
export PYTHONPATH=$PYTHONPATH:${saw_path}/anaconda/lib/python3.8/site-packages
${saw_path}/anaconda/bin/python -m site"

**Comment by SuqinYang** [comment]
By the way, I wonder if there is a way to be able to see the contents of the *.barcodeToPos.h5 file in the mask folder? Thanks again!

**Comment by Jinghao-Chen** [comment]
Hi, you could use `h5dump` command or python h5py to view it. The content of .h5 file is a matrix. The value of (y,x,0) represents the result of CID sequence with coordinates (x,y) on the chip after quaternary conversion. If you are interested, you could use ST_BarcodeMap to convert the h5 file into a CID sequence txt.
https://github.com/STOmics/ST_BarcodeMap
https://github.com/STOmics/ST_BarcodeMap/issues/2
