### ISSUE TITLE
Error:IndexError: list index out of range

### ISSUE THREAD

**Issue by SuqinYang** [STOmics/SAW#26]
Hi,sorry to trouble you. I am trying to use "stereoPipeline",and there is a bug with my codes.I don't know how to sovle it. I guess this shouldn't be a problem with the genome index, because I can run it successfully with your test data
My codes:
cd 01.stereoPipeline_output
ulimit -n 10240
ulimit -v 33170449147
export NUMBA_CACHE_DIR=01.stereoPipeline_output

dataDir=/data/rawdata/00.Rawdata
outDir=/data/01.stereoPipeline_output
index=/data/reference/mouse/
SAW=/data/software
h5=/data/rawdata/01.Filter
image=/data/04.image
export SINGULARITY_BIND=$dataDir,$outDir,$index,$SAW,$h5,$image

bash /data/home/linlab/yangsuqin/software/stereoPipeline.sh  -genomeSize 3  -splitCount 1 -maskFile $h5/SS200000314TL_C6/SS200000314TL_C6.barcodeToPos.h5 -fq1 $dataDir/SS200000314TL_C6/DP8400028095TL_L01_13_1.fq.gz,$dataDir/SS200000314TL_C6/DP8400028095TL_L01_14_1.fq.gz   -fq2 $dataDir/SS200000314TL_C6/DP8400028095TL_L01_13_2.fq.gz,$dataDir/SS200000314TL_C6/DP8400028095TL_L01_14_2.fq.gz  -speciesName mouse  -tissueType liver -refIndex $index/STAR_SJ100  -annotationFile $index/genes.gtf -imageRecordFile $image/SS200000314TL_C6_20230112_191604_1.1.3.ipr -imageCompressedFile $image/SS200000314TL_C6_20230112_191604_1.1.3.tar.gz -sif $SAW/SAW_v5.1.3.sif -threads 16 -doCellBin Y  -outDir $outDir/SS200000314TL_C6

ERROR:
2023-01-13 17:05:47.540352: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/python3/lib/python3.8/site-packages/cv2/../../lib64:/opt/lib:/.singularity.d/libs
2023-01-13 17:05:47.540553: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[INFO 20230113-17-05-52 p65806 prepare_dir main.py:304] Dir preparation completed.
I0113 17:05:52.343869 65806 main.py:304] Dir preparation completed.
[WARN 20230113-17-05-52 p65806 check_files2 main.py:328] The *_transformed.tif image could not be found under the /data/04.image/SS200000314TL_C6_20230112_191604_1.1.3.tar.gz.
W0113 17:05:52.345068 65806 main.py:328] The *_transformed.tif image could not be found under the /data/04.image/SS200000314TL_C6_20230112_191604_1.1.3.tar.gz.
[INFO 20230113-17-05-52 p65806 prepare_input main.py:355] Original data already exists, skip input preparation.
I0113 17:05:52.350958 65806 main.py:355] Original data already exists, skip input preparation.
[INFO 20230113-17-05-52 p65806 prepare_input main.py:412] Input preparation completed.
I0113 17:05:52.352168 65806 main.py:412] Input preparation completed.
[INFO 20230113-17-05-52 p65806 pipeline_entry main.py:62] Copy ipr.
I0113 17:05:52.352295 65806 main.py:62] Copy ipr.
[WARN 20230113-17-05-52 p65806 run main.py:150] Pipeline need to handle these subtask: ['cellseg', 'register', 'stitch', 'tissueseg'].
W0113 17:05:52.373524 65806 main.py:150] Pipeline need to handle these subtask: ['cellseg', 'register', 'stitch', 'tissueseg'].
[INFO 20230113-17-05-52 p65806 run main.py:166] >> Next do the stitching task.
I0113 17:05:52.373875 65806 main.py:166] >> Next do the stitching task.
[INFO 20230113-17-05-52 p65806 point_spread_into_template fov_track.py:121] Generate global template from FOV [Item, Loc, Shape] ([1, 9], [16470  2193], (24366, 25823)).
I0113 17:05:52.430801 65806 fov_track.py:121] Generate global template from FOV [Item, Loc, Shape] ([1, 9], [16470  2193], (24366, 25823)).
Traceback (most recent call last):
  File "/ldfssz1/ST_BI/USER/raozuming/pyc/stereo-resep-dev/stereo-resep/main.py", line 684, in <module>
  File "/ldfssz1/ST_BI/USER/raozuming/pyc/stereo-resep-dev/stereo-resep/main.py", line 24, in __init__
  File "/ldfssz1/ST_BI/USER/raozuming/pyc/stereo-resep-dev/stereo-resep/main.py", line 120, in pipeline_entry
  File "/ldfssz1/ST_BI/USER/raozuming/pyc/stereo-resep-dev/stereo-resep/main.py", line 172, in run
  File "/ldfssz1/ST_BI/USER/raozuming/pyc/stereo-resep-dev/stereo-resep/stitching/stitch.py", line 28, in stitch_entry
  File "/ldfssz1/ST_BI/USER/raozuming/pyc/stereo-resep-dev/stereo-resep/stitching/fov_stitching/fov_stitch.py", line 488, in stitching
  File "/ldfssz1/ST_BI/USER/raozuming/pyc/stereo-resep-dev/stereo-resep/stitching/fov_stitching/fov_stitch.py", line 432, in big_image_template
IndexError: list index out of range

**Comment by TheSallyGardens** [comment]
@SuqinYang Hi,
Could you try to use saw5.4.0?

**Comment by James-lin9** [comment]
I use saw5.40 pipeline and sif, still got same error

**Comment by Clouate** [comment]
> I use saw5.40 pipeline and sif, still got same error

@James-lin9 Hi, could you provide your imageRecordFile:
'$image/SS200000314TL_C6_20230112_191604_1.1.3.ipr' for us?

**Comment by SuqinYang** [comment]
***@***.***@Clouate
I used saw5.40 pipeline, and still got the same error.Here is my  'SS200000314TL_C6_20230112_191604_1.1.3.ipr'

2023-01-21 03:10:44KentLE ***@***.***>写道：




I use saw5.40 pipeline and sif, still got same error

@James-lin9 Hi, could you provide your imageRecordFile:
'$image/SS200000314TL_C6_20230112_191604_1.1.3.ipr' for us?
