### ISSUE TITLE
Pygame init error while building singularity image

### ISSUE THREAD

**Issue by vladimirkovacevic** [STOmics/SAW#36]
I'm trying to run SAW on Ubuntu AWS instance and run into the issue while building singularity container. All the steps before it are completed according to provided instructions. When I run:
'singularity build SAW_05_5_3.sif stomics/saw:05.5.3'
I'm getting the following error:
```

Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
Running under Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
pygame 2.1.2 (SDL 2.0.20, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/ubuntu/.local/share/singularity/log/error.log (lazily created when something is logged)
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
Traceback (most recent call last):
  File "/usr/games/singularity", line 11, in <module>
    load_entry_point('Endgame-Singularity==1.0', 'gui_scripts', 'singularity')()
  File "/usr/lib/python3/dist-packages/singularity/__init__.py", line 349, in main
    pygame.key.set_repeat(500, 50)
pygame.error: video system not initialized
```
It is a common error and many suggest that `pygame.init()` should be run. That would mean changing singularity source code. Do you have any suggestions on how to resolve this issue?

**Comment by TheSallyGardens** [comment]
@vladimirkovacevic Hi!
It is recommended to use version 3.8 or higher of Singularity
