### ISSUE TITLE
Report generation error:  inconsistent rpi file naming across pipeline steps?

### ISSUE THREAD

**Issue by vdet** [STOmics/SAW#49]
Hello, I am trying to run the SAW 6.0.1 pipeline on the mouse embryo slice E16.5_E2S7 from the Cell paper.
Report generation seems to request a rpi file with a name not matching rpi file names generated at earlier steps.

The following error message was produced:
```
[...]
Tue 16 May 2023 05:40:21 AM CEST => report generation start......
WARNING: DEPRECATED USAGE: Environment variable SINGULARITY_BIND will not be supported in the future, use APPTAINER_BIND instead
/usr/local/python3/lib/python3.8/site-packages/seaborn/distributions.py:2619: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `kdeplot` (an axes-level function for kernel density plots).
[... #more deprecation warnings]
  warnings.warn(msg, FutureWarning)
/usr/local/python3/lib/python3.8/site-packages/seaborn/distributions.py:2103: FutureWarning: The `axis` variable is no longer used and will be removed. Instead, assign variables directly to `x` or `y`.
  warnings.warn(msg, FutureWarning)
Traceback (most recent call last):
  File "report/handleReport_main.py", line 416, in <module>
  File "report/handleReport_main.py", line 363, in main
  File "report/generate_analysis_report.py", line 256, in generate_html_function
  File "report/generate_analysis_report.py", line 1433, in find_bg_images_info
  File "report/generate_analysis_report.py", line 1477, in get_init_image_info
  File "/usr/local/python3/lib/python3.8/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/usr/local/python3/lib/python3.8/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/basedir/stereo-seq-test/mouse-embryo/E16.5_E2S7/preprocessed/03.register/E16.rpi', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```
the ```03.register``` folder does contain ```rpi``` files, but it's not ```E16.rpi```:
```
$ ls 03.register/*rpi
03.register/fov_stitched_transformed.rpi  03.register/SS200000116TL_F3.rpi
```

The pipeline was invoked with:
```
container=/basedir/vms/SAW_v6.0.1.sif
baseDir=/basedir/stereo-seq-test/mouse-embryo/E16.5_E2S7
genomeDir=/basedir/stereo-seq-test/mouse-embryo/mouse-genome
dataDir=$baseDir/raw
outDir=$baseDir/preprocessed

export SINGULARITY_BIND=$dataDir,$outDir,$genomeDir

# run pipeline - Scenario 1: input image and run cell bin
bash /basedir/stereo-seq-test/mouse-embryo/scripts/stereoPipeline_v6.0.0.sh -sif $container -genomeSize 3 -splitCount 1 -maskFile $dataDir/E16.5_E2S7.barcodeToPos.h5 -fq1 $dataDir/CNR0505880/FP200003803_L01_72_1.fq.gz,$dataDir/CNR0505881/FP200003803_L01_73_1.fq.gz,$dataDir/CNR0505882/FP200003803_L01_74_1.fq.gz,$dataDir/CNR0505883/FP200003803_L01_76_1.fq.gz,$dataDir/CNR0505884/FP200003803_L01_77_1.fq.gz,$dataDir/CNR0505885/FP200003803_L01_78_1.fq.gz -fq2 $dataDir/CNR0505880/FP200003803_L01_72_2.fq.gz,$dataDir/CNR0505881/FP200003803_L01_73_2.fq.gz,$dataDir/CNR0505882/FP200003803_L01_74_2.fq.gz,$dataDir/CNR0505883/FP200003803_L01_76_2.fq.gz,$dataDir/CNR0505884/FP200003803_L01_77_2.fq.gz,$dataDir/CNR0505885/FP200003803_L01_78_2.fq.gz -speciesName mouse -tissueType E16.5_E2S7 -refIndex $genomeDir/STAR_NCBI_mm39 -genomeFile $genomeDir/ncbi_dataset/data/GCF_000001635.27/GCF_000001635.27_GRCm39_genomic.fna -annotationFile $genomeDir/ncbi_dataset/data/GCF_000001635.27/genomic.gff -threads 20 -outDir $outDir -imageCompressedFile $dataDir/QCImgUpload_E16.5_E2S7/SS200000116TL_F3_20230512_173830_1.1.3.tar.gz -imageRecordFile $dataDir/QCImgUpload_E16.5_E2S7/SS200000116TL_F3_20230512_173830_1.1.3.ipr -doCellBin Y
``` 
Please let me now if more information is needed.
All the best.

**Comment by TheSallyGardens** [comment]
You can run the report separately and enter the correct rpi file.
 Best~
