### ISSUE TITLE
SAW-A40704 in Manual_part2

### ISSUE THREAD

**Issue by JungTaeKim103** [STOmics/SAW#92]
Hello. I need help with an issue I'm encountering. I am attempting to perform manual registration on a file obtained from streomap. To do this, I executed manual_part2.sh. Here is the execution history:

```
(base) Minhos@anode3:~/R/Stereoseq$ cd /home/users/Minhos/R/Stereoseq/ && bash stereoPipeline_v7.0_manual_part2.sh     -SN B03020E6     -dataDir /home/users/Minhos/R/Stereoseq/results_control     -registJson /home/users/Minhos/R/Stereoseq/results_control/03.register/Regist/20240207115016.regist.json     -speciesName Mouse     -tissueType Brain     -outDir /home/users/Minhos/R/Stereoseq/results_control_MR/     -imageRecordFile /home/users/Minhos/R/Stereoseq/Mouse-Brain-Control/B03020E6_SC_20240117_135843_3.0.2.ipr     -imageCompressedFile /home/users/Minhos/R/Stereoseq/Mouse-Brain-Control/B03020E6_SC_20240117_135843_3.0.2.tar.gz     -doCellBin Y     -threads 20     -sif /home/users/Minhos/SAW_7.0.sif
Thu Feb 15 15:09:51 KST 2024  singularity check: pass, and singularity path is /usr/local/bin/singularity
Thu Feb 15 15:09:51 KST 2024  singularity image file check: file exist and SIF path is /home/users/Minhos/SAW_7.0.sif
Thu Feb 15 15:09:52 KST 2024 => image processing and registration start.......
WARNING: While bind mounting '/home/users/Minhos/R/Stereoseq/Mouse-Brain-Control:/home/users/Minhos/R/Stereoseq/Mouse-Brain-Control': destination is already in the mount point list
STEREOmics REgistration and SEgmentation Pipeline (STEREO-RESEP)
Namespace(adaptive=False, flip=0, func=<class '__main__.SemiAutomaticPipeline'>, input='/home/users/Minhos/R/Stereoseq/results_control/03.register', ipr='/home/users/Minhos/R/Stereoseq/results_control_MR//03.register/B03020E6.reregist.ipr', manual_rot=0.0, map='', offset=[-890.0, 940.0], output='/home/users/Minhos/R/Stereoseq/results_control_MR//03.register', scale=[0.0, 0.0], vis='/home/users/Minhos/R/Stereoseq/results_control/02.count/B03020E6.raw.gef', whether_reverse=False) []
[WARN 20240215-15-09-56 p1661418 _get_input semi_automatic.py:116] This -a or --adaptive parameter is not used in this version.
[INFO 20240215-15-09-56 p1661418 pipeline_entry semi_automatic.py:181] Next update: registration info.
[INFO 20240215-15-09-59 p1661418 pre_check_vis semi_automatic.py:273] No validation on gene sequencing matrix.
[INFO 20240215-15-09-59 p1661418 synchronize_group_data common.py:192] no need to copy Register group.
[INFO 20240215-15-09-59 p1661418 pipeline_entry semi_automatic.py:245] Manual registration succeeded.
        Command being timed: "singularity exec /home/users/Minhos/SAW_7.0.sif manualRegister -i /home/users/Minhos/R/Stereoseq/results_control/03.register -c /home/users/Minhos/R/Stereoseq/results_control_MR//03.register/B03020E6.reregist.ipr -v /home/users/Minhos/R/Stereoseq/results_control/02.count/B03020E6.raw.gef -f 0 -r 0 -o -890 940 -s 0 0 -a False -p /home/users/Minhos/R/Stereoseq/results_control_MR//03.register"
        User time (seconds): 152.41
        System time (seconds): 15.89
        Percent of CPU this job got: 2172%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:07.74
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 838776
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1127
        Minor (reclaiming a frame) page faults: 67328
        Voluntary context switches: 29090
        Involuntary context switches: 1772
        Swaps: 0
        File system inputs: 233152
        File system outputs: 48
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
WARNING: While bind mounting '/home/users/Minhos/R/Stereoseq/Mouse-Brain-Control:/home/users/Minhos/R/Stereoseq/Mouse-Brain-Control': destination is already in the mount point list
Namespace(conf='/home/users/Minhos/R/Stereoseq/results_control_MR//03.register/B03020E6.reregist.ipr', func=<function ipr2img at 0x146a67cd7d30>, input='/home/users/Minhos/R/Stereoseq/Mouse-Brain-Control/B03020E6_SC_20240117_135843_3.0.2.tar.gz', module=['tissue', 'cell'], output='/home/users/Minhos/R/Stereoseq/results_control_MR//03.register', register=True) []
[INFO 20240215-15-10-12 p1662200 tar_decompress ipr_to_image.py:294] Extract files from tar.gz file completed.
[INFO 20240215-15-10-21 p1662200 main ipr_to_image.py:728] Save ssDNA_fov_stitched_transformed.tif success.
[WARN 20240215-15-10-21 p1662200 main ipr_to_image.py:735] Failed to generate transform_template.txt template.
[WARN 20240215-15-10-21 p1662200 main ipr_to_image.py:781] Failed to generate matrix_template.txt template.
[INFO 20240215-15-10-21 p1662200 register ipr_to_image.py:555] Rotate and scale the radiation matrix: [1.0, 0.0, 0.0, 1.0] after manual registration
[INFO 20240215-15-10-22 p1662200 register ipr_to_image.py:571] Manually register the width: 20580 and height: 23516 after affine transformation
[INFO 20240215-15-10-30 p1662200 main ipr_to_image.py:818] Save ssDNA_B03020E6_regist.tif success
[ERRO 20240215-15-10-30 p1662200 main ipr_to_image.py:835] SAW-A40704:    Automatic Tissue cut or hand Tissue cut has not been completed,tissue cut cannot be done, in StereoResepSwitch -> tissueseg is TRUE or ManualState -> tissueseg is FALSE.
Traceback (most recent call last):
  File "imageTools/main.py", line 105, in <module>
  File "imageTools/main.py", line 101, in main
  File "imageTools/main.py", line 18, in ipr2img
  File "imageTools/ipr_to_image/ipr_to_image.py", line 234, in __init__
  File "imageTools/ipr_to_image/ipr_to_image.py", line 839, in main
Exception: SAW-A40704:    Automatic Tissue cut or hand Tissue cut has not been completed,tissue cut cannot be done, in StereoResepSwitch -> tissueseg is TRUE or ManualState -> tissueseg is FALSE.
Command exited with non-zero status 1
        Command being timed: "singularity exec /home/users/Minhos/SAW_7.0.sif imageTools ipr2img -i /home/users/Minhos/R/Stereoseq/Mouse-Brain-Control/B03020E6_SC_20240117_135843_3.0.2.tar.gz -c /home/users/Minhos/R/Stereoseq/results_control_MR//03.register/B03020E6.reregist.ipr -d tissue cell -r True -o /home/users/Minhos/R/Stereoseq/results_control_MR//03.register"
        User time (seconds): 45.00
        System time (seconds): 23.92
        Percent of CPU this job got: 219%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:31.35
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 2881164
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1088
        Minor (reclaiming a frame) page faults: 84727
        Voluntary context switches: 55933
        Involuntary context switches: 4013
        Swaps: 0
        File system inputs: 213024
        File system outputs: 5022824
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 1
```
Upon inspecting the SN.reregist.ipr file, I noticed that the ManualState register is set to TRUE and the StereoResepSwitch to FALSE. Could this be causing the problem? How can I modify these values?

**Comment by Jinghao-Chen** [comment]
Hi, the parameter `-imageRecordFile` should be the ipr file in the 03.register directory output by the SAW pipeline you ran before.
Before re-running the bash, it is recommended to delete the SN.reregist.ipr manually

**Comment by JungTaeKim103** [comment]
Oh. It is working.

I appreciate you
