### ISSUE TITLE
failed to register

### ISSUE THREAD

**Issue by Sooooooooda** [STOmics/SAW#94]
[ERRO 20240220-20-16-12 p2444396 create_auto_manual_attrs main.py:210] SAW-A40001:    The version of 0.1.0 is too low to deliver automatic registration.
E0220 20:16:12.480310 2444396 main.py:210] SAW-A40001:    The version of 0.1.0 is too low to deliver automatic registration.
Traceback (most recent call last):
  File "register/register-4.2.4/register/main.py", line 521, in <module>
  File "register/register-4.2.4/register/main.py", line 517, in main
  File "register/register-4.2.4/register/main.py", line 335, in __init__
  File "register/register-4.2.4/register/main.py", line 211, in create_auto_manual_attrs
Exception: SAW-A40001:    The version of 0.1.0 is too low to deliver automatic registration.
When I run 'singularity exec SAW_7.0.sif register' command, I raises this error.
How to solve it,thank you

**Comment by Jinghao-Chen** [comment]
Hi, which version of ImageStudio did you use to generate .tar.gz and .ipr? This error is often due to the version of ImageStudio being too low and not suitable for SAW 7.0.0. For SAW(v>=7.0.0), you could use the latest version of imagestudio (>=3.0.0) to QC the microscope images and regenerate the .tar.gz and .ipr.
