### ISSUE TITLE
Manual Registration part 2 failure

### ISSUE THREAD

**Issue by raforsyth** [STOmics/SAW#95]
I'm running part two of the SAW pipeline using manual registration. The first part goes through fine, but when I run the second part I receive the following output and it fails.
```
[WARN 20240219-15-43-02 p2118883 _get_input semi_automatic.py:116] This -a or --adaptive parameter is not used in this version.
[INFO 20240219-15-43-02 p2118883 pipeline_entry semi_automatic.py:181] Next update: registration info.
[INFO 20240219-15-43-04 p2118883 pre_check_vis semi_automatic.py:259] Validation of Gene Sequencing Matrix.
[INFO 20240219-15-43-04 p2118883 pre_check_vis semi_automatic.py:271] Gene sequencing matrix check is successful.
[INFO 20240219-15-43-04 p2118883 pipeline_entry semi_automatic.py:245] Manual registration succeeded.
	Command being timed: "singularity exec SAW_7.0.sif manualRegister -i /result/03.register/manual_register -c /result/03.register/D01871D6.reregist.ipr -v /result/02.count/D01871D6.raw.gef -f 1 -r 176.02 -o -520 -4110 -s -0.22399999999999998 -0.226 -a False -p /staging/leuven/stg_00096/home/rforsyth/stereo_seq/V350133897/result/03.register"
	User time (seconds): 28.33
	System time (seconds): 4.76
	Percent of CPU this job got: 114%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:29.00
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1039488
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 3005
	Minor (reclaiming a frame) page faults: 125861
	Voluntary context switches: 363662
	Involuntary context switches: 296
	Swaps: 0
	File system inputs: 3015768
	File system outputs: 64
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
INFO:    Environment variable SINGULARITY_BIND is set, but APPTAINER_BIND is preferred
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
[INFO 20240219-15-43-18 p2119042 tar_decompress ipr_to_image.py:294] Extract files from tar.gz file completed.
[INFO 20240219-15-43-20 p2119042 main ipr_to_image.py:728] Save ssDNA_fov_stitched_transformed.tif success.
[WARN 20240219-15-43-20 p2119042 main ipr_to_image.py:735] Failed to generate transform_template.txt template.
[WARN 20240219-15-43-20 p2119042 main ipr_to_image.py:781] Failed to generate matrix_template.txt template.
[INFO 20240219-15-43-20 p2119042 register ipr_to_image.py:555] Rotate and scale the radiation matrix: [0.7741285511315751, 0.053721988563382055, 0.05386080507129777, -0.7721333744534009] after manual registration
[INFO 20240219-15-43-21 p2119042 register ipr_to_image.py:571] Manually register the width: 26460 and height: 26459 after affine transformation
[INFO 20240219-15-43-21 p2119042 main ipr_to_image.py:818] Save ssDNA_D01871D6_regist.tif success
[ERRO 20240219-15-43-21 p2119042 main ipr_to_image.py:835] SAW-A40704:    Automatic Tissue cut or hand Tissue cut has not been completed,tissue cut cannot be done, in StereoResepSwitch -> tissueseg is TRUE or ManualState -> tissueseg is FALSE.
Traceback (most recent call last):
  File "imageTools/main.py", line 105, in <module>
  File "imageTools/main.py", line 101, in main
  File "imageTools/main.py", line 18, in ipr2img
  File "imageTools/ipr_to_image/ipr_to_image.py", line 268, in __init__
  File "imageTools/ipr_to_image/ipr_to_image.py", line 839, in main
Exception: SAW-A40704:    Automatic Tissue cut or hand Tissue cut has not been completed,tissue cut cannot be done, in StereoResepSwitch -> tissueseg is TRUE or ManualState -> tissueseg is FALSE.
Command exited with non-zero status 1
	Command being timed: "singularity exec SAW_7.0.sif imageTools ipr2img -i D01871D6_20231017_112824_1.1.3.tar.gz -c result/03.register/D01871D6.reregist.ipr -d tissue -r True -o /result/03.register"
	User time (seconds): 32.45
	System time (seconds): 8.46
	Percent of CPU this job got: 236%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:17.30
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 3375368
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 1291
	Minor (reclaiming a frame) page faults: 156651
	Voluntary context switches: 385916
	Involuntary context switches: 10115
	Swaps: 0
	File system inputs: 1472512
	File system outputs: 6099880
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1

```
Is there a way to fix this issue? I'm not sure what's going on

**Comment by Jinghao-Chen** [comment]
Hi, was your image QC failed? If so, you could import the ipr file and tar.gz into imagestudio for manual tissue segmentation and output the new ipr file, as the input of the part2 script. If QC was successed, please find the ipr file in the output directory 03.register of part1 as the input of the part2 script.

**Comment by raforsyth** [comment]
The image did pass QC on ImageQC, however I did receive the following message when running the part 1 of the SAW pipeline which seemed odd. 

```
[WARN 20240216-20-59-43 p3977605 main ipr_to_image.py:735] Failed to generate transform_template.txt template.
```
When I ran part 2 of the script with the ipr file from 03.register, it crashes and I receive this error

```
cp: 'result/03.register/D01871D6.reregist.ipr' and 'result/03.register/D01871D6.reregist.ipr' are the same file
```

**Comment by Jinghao-Chen** [comment]
Hi, could you change your output directory in the part2 bash and try again?
parameter: `-outDir`
And the name of the ipr file output from part1.sh is like 'SN_SC_20240130_105819_3.0.2.ipr', could you comfirm it?

**Comment by raforsyth** [comment]
I only have a file of the form SN.reregist.ipr in the 03.register folder, part1.sh didn't seem to generate any files of that form in 03.register for me

**Comment by Jinghao-Chen** [comment]
I'm sorry, it seems that you did not run the [stereoPipeline_v7.0.sh](https://github.com/STOmics/SAW/blob/main/Scripts/stereoPipeline_v7.0.sh)
So you could import the ipr file and tar.gz into ImageStudio for manual tissue segmentation, and cell segmentation if you need, and output the new ipr file as the input of the part2 script.

**Comment by raforsyth** [comment]
So I need to run the original full stereo pipeline and then take the .ipr image that comes from 03.register from that run? I have previously run the full stereo pipeline before and the image registration placed the image incorrectly.

I'd thought that the solution to that was to separately run step 1 and step 2 of the manual pipeline

**Comment by raforsyth** [comment]
I have now run it using a .ipr image matching the form you described from my first run of the full pipeline, but I have unfortunately the exact same error as before 

```
[WARN 20240219-15-43-02 p2118883 _get_input semi_automatic.py:116] This -a or --adaptive parameter is not used in this version.
[INFO 20240219-15-43-02 p2118883 pipeline_entry semi_automatic.py:181] Next update: registration info.
[INFO 20240219-15-43-04 p2118883 pre_check_vis semi_automatic.py:259] Validation of Gene Sequencing Matrix.
[INFO 20240219-15-43-04 p2118883 pre_check_vis semi_automatic.py:271] Gene sequencing matrix check is successful.
[INFO 20240219-15-43-04 p2118883 pipeline_entry semi_automatic.py:245] Manual registration succeeded.
	Command being timed: "singularity exec SAW_7.0.sif manualRegister -i /result/03.register/manual_register -c /result/03.register/D01871D6.reregist.ipr -v /result/02.count/D01871D6.raw.gef -f 1 -r 176.02 -o -520 -4110 -s -0.22399999999999998 -0.226 -a False -p /staging/leuven/stg_00096/home/rforsyth/stereo_seq/V350133897/result/03.register"
	User time (seconds): 28.33
	System time (seconds): 4.76
	Percent of CPU this job got: 114%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:29.00
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1039488
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 3005
	Minor (reclaiming a frame) page faults: 125861
	Voluntary context switches: 363662
	Involuntary context switches: 296
	Swaps: 0
	File system inputs: 3015768
	File system outputs: 64
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
INFO:    Environment variable SINGULARITY_BIND is set, but APPTAINER_BIND is preferred
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
[INFO 20240219-15-43-18 p2119042 tar_decompress ipr_to_image.py:294] Extract files from tar.gz file completed.
[INFO 20240219-15-43-20 p2119042 main ipr_to_image.py:728] Save ssDNA_fov_stitched_transformed.tif success.
[WARN 20240219-15-43-20 p2119042 main ipr_to_image.py:735] Failed to generate transform_template.txt template.
[WARN 20240219-15-43-20 p2119042 main ipr_to_image.py:781] Failed to generate matrix_template.txt template.
[INFO 20240219-15-43-20 p2119042 register ipr_to_image.py:555] Rotate and scale the radiation matrix: [0.7741285511315751, 0.053721988563382055, 0.05386080507129777, -0.7721333744534009] after manual registration
[INFO 20240219-15-43-21 p2119042 register ipr_to_image.py:571] Manually register the width: 26460 and height: 26459 after affine transformation
[INFO 20240219-15-43-21 p2119042 main ipr_to_image.py:818] Save ssDNA_D01871D6_regist.tif success
[ERRO 20240219-15-43-21 p2119042 main ipr_to_image.py:835] SAW-A40704:    Automatic Tissue cut or hand Tissue cut has not been completed,tissue cut cannot be done, in StereoResepSwitch -> tissueseg is TRUE or ManualState -> tissueseg is FALSE.
Traceback (most recent call last):
  File "imageTools/main.py", line 105, in <module>
  File "imageTools/main.py", line 101, in main
  File "imageTools/main.py", line 18, in ipr2img
  File "imageTools/ipr_to_image/ipr_to_image.py", line 268, in __init__
  File "imageTools/ipr_to_image/ipr_to_image.py", line 839, in main
Exception: SAW-A40704:    Automatic Tissue cut or hand Tissue cut has not been completed,tissue cut cannot be done, in StereoResepSwitch -> tissueseg is TRUE or ManualState -> tissueseg is FALSE.
Command exited with non-zero status 1
	Command being timed: "singularity exec SAW_7.0.sif imageTools ipr2img -i D01871D6_20231017_112824_1.1.3.tar.gz -c result/03.register/D01871D6.reregist.ipr -d tissue -r True -o /result/03.register"
	User time (seconds): 32.45
	System time (seconds): 8.46
	Percent of CPU this job got: 236%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:17.30
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 3375368
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 1291
	Minor (reclaiming a frame) page faults: 156651
	Voluntary context switches: 385916
	Involuntary context switches: 10115
	Swaps: 0
	File system inputs: 1472512
	File system outputs: 6099880
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
```

**Comment by Jinghao-Chen** [comment]
Maybe it would be better to try using ImageStudio for manual tissue segmentation. I think the ipr files in these directories have been mixed

**Comment by raforsyth** [comment]
I have rerun imageQC completely, it passed, and I used the results to rerun the latest version of the SAW part 1 pipeline. When I run it I only get 4 files in the 03.register folder (in manual_register/). a .SNchipNo.gef, expnum.tif, ssDNA_fov_stitched_transformed.tif. I get the following errors when running the pipeline.

```
[INFO 20240405-16-33-37 p4125701 tar_decompress ipr_to_image.py:294] Extract files from tar.gz file completed.
[INFO 20240405-16-33-39 p4125701 main ipr_to_image.py:728] Save ssDNA_fov_stitched_transformed.tif success.
[WARN 20240405-16-33-39 p4125701 main ipr_to_image.py:735] Failed to generate transform_template.txt template.
	Command being timed: "singularity exec path/to/SAW_07.1.0.sif imageTools ipr2img -i path/to/SNChip.tar.gz -c path/to/SNChip_num.ipr -r False -o path/to/result/03.register/manual_register"
	User time (seconds): 16.85
	System time (seconds): 6.27
	Percent of CPU this job got: 106%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:21.72
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1993780
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 843
	Minor (reclaiming a frame) page faults: 146316
	Voluntary context switches: 156711
	Involuntary context switches: 4037
	Swaps: 0
	File system inputs: 1469744
	File system outputs: 3364840
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
basename: missing operand
Try 'basename --help' for more information.
INFO:    Environment variable SINGULARITY_BIND is set, but APPTAINER_BIND is preferred
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
INFO:    fuse: warning: library too old, some operations may not work
Matplotlib created a temporary cache directory at /tmp/matplotlib-2trsad67 because the default path (path/to/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
usage: Widgets for working with images img2rpi [-h] [-i INPUT] [-o OUTPUT]
                                               [-g GROUP] [-b BIN [BIN ...]]
                                               [-c COLOR]
Widgets for working with images img2rpi: error: argument -i/--input: expected one argument
Command exited with non-zero status 2
	Command being timed: "singularity exec path/to/SAW_07.1.0.sif imageTools img2rpi -i -g /Image -b 1 10 50 100 -o path/to/result/03.register/manual_register/fov_stitched.rpi"
	User time (seconds): 4.37
	System time (seconds): 2.13
	Percent of CPU this job got: 105%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:06.16
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 296388
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 827
	Minor (reclaiming a frame) page faults: 127111
	Voluntary context switches: 140672
	Involuntary context switches: 205
	Swaps: 0
	File system inputs: 357904
	File system outputs: 64
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 2
```

**Comment by TheSallyGardens** [comment]
@raforsyth Hi.
SAW:07.1.0.sif requires tar.gz and ipr files produced by imagestudio V3.I hope this will be helpful to you.

**Comment by lvmt** [comment]
running code  

```
echo `date` "=> image processing and registration start......."
export HDF5_USE_FILE_LOCKING=FALSE
dataDir='/xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/QC/bgi/WK010'

imageTarFile='/xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/rawData/musBrain_WK010/ImageStudio_QC/D03257E614_20240822_114652/D03257E614_SC_20240822_114652_3.0.4.tar.gz'

iprFile='/xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/rawData/musBrain_WK010/ImageStudio_QC/D03257E614_20240822_114652/D03257E614_SC_20240822_114652_3.0.4.ipr'

#iprFile='/xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/QC/bgi/WK010/03.register/manual_ipr/D03257E614_SC_20240925_111918_3.0.4.ipr'

registJson='/xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/QC/bgi/WK010/03.register/manual_register/20240925093324.regist.json'

imgTarDIR=$(dirname $imageTarFile)
iprDIR=$(dirname $iprFile)
SN='D03257E614'


sif='/xskydata/apps/singularity/SAW/SAW_7.1.sif'


export SINGULARITY_BIND=$outDir,$imgTarDIR,$iprDIR,$dataDir

cp -rf ${iprFile} ${dataDir}/03.register/${SN}.reregist.ipr

offsetX=`cat ${registJson} | sed 's/,/\n/g' | grep "offsetX" | sed 's/:/\n/g' | sed '1d' | sed 's/}//g'|sed 's/"//g'`
offsetY=`cat ${registJson} | sed 's/,/\n/g' | grep "offsetY" | sed 's/:/\n/g' | sed '1d' | sed 's/}//g'|sed 's/"//g'`
flip=`cat ${registJson} | sed 's/,/\n/g' | grep "flip" | sed 's/:/\n/g' | sed '1d' | sed 's/}//g'|sed 's/"//g'`
rotate=`cat ${registJson} | sed 's/,/\n/g' | grep "rotate" | sed 's/:/\n/g' | sed '1d' | sed 's/}//g'|sed 's/"//g'`
isTunedStr=`cat ${registJson} | sed 's/,/\n/g' | grep "isTuned" | sed 's/:/\n/g' | sed '1d' | sed 's/}//g'|sed 's/"//g'`
extrude_x=`cat ${registJson} | sed 's/,/\n/g' | grep "extrude_x" | sed 's/:/\n/g' | sed '1d' | sed 's/}//g'|sed 's/"//g'`
extrude_y=`cat ${registJson} | sed 's/,/\n/g' | grep "extrude_y" | sed 's/:/\n/g' | sed '1d' | sed 's/}//g'|sed 's/"//g'`
if [[ isTunedStr == 'true' ]];then isTuned='True';else isTuned='False';fi

#/usr/bin/time -v singularity exec ${sif} manualRegister \
#	-i ${dataDir}/03.register/manual_register \
#	-c ${dataDir}/03.register/${SN}.reregist.ipr \
#	-v ${dataDir}/02.count/${SN}.raw.gef  \
#	-f $flip \
#	-r $rotate \
#	-o $offsetX $offsetY \
#	-s $extrude_x $extrude_y \
#	-a $isTuned \
#	-p ${dataDir}/03.register/aa



out_iprFile=$(find ${dataDir}/03.register/ -maxdepth 1 -name \*.ipr | head -1)
/usr/bin/time -v singularity exec ${sif} imageTools ipr2img \
	-i ${imageTarFile} \
	-c ${out_iprFile}  \
	-d tissue cell \
	-r True \
	-o ${dataDir}/03.register/ 
```

error message
```
Wed Sep 25 14:34:26 CST 2024 => image processing and registration start.......
WARNING: While bind mounting '/xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/rawData/musBrain_WK010/ImageStudio_QC/D03257E614_20240822_114652:/xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/rawData/musBrain_WK010/ImageStudio_QC/D03257E614_20240822_114652': destination is already in the mount point list
Namespace(conf='/xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/QC/bgi/WK010/03.register/D03257E614.reregist.ipr', func=<function ipr2img at 0x1499caf86ca0>, input='/xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/rawData/musBrain_WK010/ImageStudio_QC/D03257E614_20240822_114652/D03257E614_SC_20240822_114652_3.0.4.tar.gz', module=['tissue', 'cell'], output='/xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/QC/bgi/WK010/03.register/', register=True) []
[INFO 20240925-14-34-36 p925703 tar_decompress ipr_to_image.py:294] Extract files from tar.gz file completed.
[INFO 20240925-14-34-36 p925703 main ipr_to_image.py:632] Use the RippleStitch stitching algorithm to calculate the stitching coordinates for stitching.
[INFO 20240925-14-34-38 p925703 main ipr_to_image.py:728] Save ssDNA_fov_stitched.tif success.
[WARN 20240925-14-34-38 p925703 main ipr_to_image.py:735] Failed to generate transform_template.txt template.
[ERRO 20240925-14-34-38 p925703 main ipr_to_image.py:742] SAW-A40704:    Automatic registration or hand registration has not been completed, registration cannot be done, ManualState group not in ipr file.
Traceback (most recent call last):
  File "imagetools-1.7.6/main.py", line 105, in <module>
  File "imagetools-1.7.6/main.py", line 101, in main
  File "imagetools-1.7.6/main.py", line 18, in ipr2img
  File "imagetools-1.7.6/ipr_to_image/ipr_to_image.py", line 234, in __init__
  File "imagetools-1.7.6/ipr_to_image/ipr_to_image.py", line 745, in main
Exception: SAW-A40704:    Automatic registration or hand registration has not been completed, registration cannot be done, ManualState group not in ipr file.
Command exited with non-zero status 1
	Command being timed: "singularity exec /xskydata/apps/singularity/SAW/SAW_7.1.sif imageTools ipr2img -i /xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/rawData/musBrain_WK010/ImageStudio_QC/D03257E614_20240822_114652/D03257E614_SC_20240822_114652_3.0.4.tar.gz -c /xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/QC/bgi/WK010/03.register/D03257E614.reregist.ipr -d tissue cell -r True -o /xskydata/project/spatialTranscriptomics/2024/Q3/spatial_transcript_mus.2024.9.23/QC/bgi/WK010/03.register/"
	User time (seconds): 15.08
	System time (seconds): 70.35
	Percent of CPU this job got: 718%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:11.89
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1087032
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 1431
	Minor (reclaiming a frame) page faults: 925284
	Voluntary context switches: 39931
	Involuntary context switches: 100151
	Swaps: 0
	File system inputs: 199646
	File system outputs: 1635992
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1

```

**QC fail** 

what should I do.

**Comment by Jinghao-Chen** [comment]
@lvmt  Hi, It seems that you have commented out the running code part of manualRegister, so ipr2img reported an error. If you do not want to perform registration and run `imageTools ipr2img` directly, change the parameter `-r True` to `-r False`. If you have other questions, please feel free to describe them in [issue 115](https://github.com/STOmics/SAW/issues/151)
