### ISSUE TITLE
cellCluster Failed 

### ISSUE THREAD

**Issue by myshu2017-03-14** [STOmics/SAW#99]
I recently ran an error using the main program. One of the two samples failed.

The error message is as follows:
>Traceback (most recent call last):
  File "cellCluster/cell_cluster.py", line 137, in <module>
  File "cellCluster/cell_cluster.py", line 131, in main
  File "cellCluster/cell_cluster.py", line 52, in cell_cluster
  File "/usr/local/python3/lib/python3.8/site-packages/stereo/core/st_pipeline.py", line 39, in wrapped
    res = func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/stereo/core/st_pipeline.py", line 524, in highly_variable_genes
    hvg.fit()
  File "/usr/local/python3/lib/python3.8/site-packages/stereo/tools/highly_variable_genes.py", line 97, in fit
    df = highly_variable_genes_single_batch(
  File "/usr/local/python3/lib/python3.8/site-packages/stereo/algorithm/highly_variable_genes.py", line 103, in highly_variable_genes_single_batch
    disp_cut_off = dispersion_norm[n_top_genes - 1]
IndexError: index 2999 is out of bounds for axis 0 with size 1304
Command being timed: "singularity exec SAW_6.1.sif cellCluster -i /data/041.cellcut/SN.cellbin.gef -o /data/051.cellcluster/SN.cell.cluster.h5ad"

What is the cause of this error?

Best wishes,
Myshu

**Comment by Jinghao-Chen** [comment]
Hi, because the number of gene types in your gene expression matrix(cellbin) is lower than 3000

**Comment by myshu2017-03-14** [comment]
> Hi, because the number of gene types in your gene expression matrix(bin200) is lower than 3000

How can I solve this error？

**Comment by Jinghao-Chen** [comment]
I'm sorry, this problem could not be adjusted in SAW's default process due to the small number of genes in each cellbin. You could try referring to Stereopy's cellbin clustering tutorial to adjust the parameters of the filtering step.
https://stereopy.readthedocs.io/en/latest/Tutorials/CellBin_Clustering.html
